### ISSUE TITLE
Importing Python bindings gives "TypeError: _argtypes_ must be a sequence of types"

### ISSUE THREAD

**Issue by rffontenelle** [libproxy/libproxy#125]
This happens on both Python 2.7.18 and 3.8.3, Arch Linux, libproxy 0.4.15 (commit 454a499)

EDIT: last check with Python 3.9.0, libproxy 0.4.16

To reproduce:
```
$ python -m libproxy
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/libproxy.py", line 48, in <module>
    _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p)
TypeError: _argtypes_ must be a sequence of types
```
or interactively:
```
$ python
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libproxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/libproxy.py", line 48, in <module>
    _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p)
TypeError: _argtypes_ must be a sequence of types
>>>
```

**Comment by bigon** [comment]
This is quite a problem, an idea?

**Comment by DimStar77** [comment]
Can you please test with the diff from #147?

**Comment by bigon** [comment]
The following minimal change seems to fix the problem in `bindings/python/libproxy.py`:

``` patch
- _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p)
+ _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p),
```
Also, why is it a `c_void_p` instead of a `c_char_p`type? `px_proxy_factory_free_proxies` takes a `char **` (I don't know anything about python and ctypes)

**Comment by DimStar77** [comment]
Your diff results in the same error as mine - when one actually tries to really use the bindings

**Comment by DimStar77** [comment]
#147 should now be ok - I can load, query and unload the library, tested with python 3.8.6

**Comment by DimStar77** [comment]
The error actually snuck in in commit d52cc344

**Comment by bigon** [comment]
@DimStar77 I'm a MR #148 that fixes this issue in addition to some cleanup
