### ISSUE TITLE
Crash on px_proxy_factory_free when using pacrunner_webkit because JSC GC is still running

### ISSUE THREAD

**Issue by thiagomacieira** [libproxy/libproxy#209]
If the Gtk-based JavaScriptCore implementation of the PAC runner is loaded, there's a good chance it'll crash when `px_proxy_factory_free()` attempts to unload the module, because the garbage collector may still be running:
```
Thread 3 "QLibProxyWrappe" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4da76c0 (LWP 415723)]
0x00007fffee96e920 in gettimeofday@plt () from /lib64/libjavascriptcoregtk-4.0.so.18
(gdb) bt
#0  0x00007fffee96e920 in gettimeofday@plt () at /lib64/libjavascriptcoregtk-4.0.so.18
#1  0x00007fffef94bb9d in  () at /lib64/libjavascriptcoregtk-4.0.so.18
#2  0x00007ffff6c92ab4 in start_thread () at /lib64/libc.so.6
#3  0x00007ffff6d19b60 in clone3 () at /lib64/libc.so.6
(gdb) thr a 2 bt

Thread 2 (Thread 0x7ffff57ff6c0 (LWP 415268) "QLibProxyWrappe"):
#0  0x00007ffff7fcb68e in _dl_debug_state () at /lib64/ld-linux-x86-64.so.2
#1  0x00007ffff7fcb1cd in _dl_close_worker () at /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7fcb64a in _dl_close () at /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7fca571 in _dl_catch_exception () at /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7fca6a3 in _dl_catch_error () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff6c8de77 in _dlerror_run () at /lib64/libc.so.6
#6  0x00007ffff6c8db86 in dlclose@GLIBC_2.2.5 () at /lib64/libc.so.6
#7  0x00007ffff71f5299 in libmodman::module_manager::~module_manager() () at /lib64/libproxy.so.1
#8  0x00007ffff71f53de in px_proxy_factory_free () at /lib64/libproxy.so.1
```

That thread was started after `JSGlobalContextCreate` is called.
```
0  0x00007ffff6c92c3e in pthread_create@GLIBC_2.2.5 () at /lib64/libc.so.6
#1  0x00007fffef94c05b in pas_scavenger_notify_eligibility_if_needed () at /lib64/libjavascriptcoregtk-4.0.so.18
#2  0x00007fffef954e78 in bmalloc_heap_config_specialized_local_allocator_try_allocate_small_segregated_slow () at /lib64/libjavascriptcoregtk-4.0.so.18
#3  0x00007fffef95668b in bmalloc_heap_config_specialized_try_allocate_common_impl_slow () at /lib64/libjavascriptcoregtk-4.0.so.18
#4  0x00007fffef95b524 in  () at /lib64/libjavascriptcoregtk-4.0.so.18
#5  0x00007fffef971a1c in  () at /lib64/libjavascriptcoregtk-4.0.so.18
#6  0x00007fffef8e2d89 in bmalloc_allocate_casual () at /lib64/libjavascriptcoregtk-4.0.so.18
#7  0x00007fffef43f8a2 in  () at /lib64/libjavascriptcoregtk-4.0.so.18
#8  0x00007ffff6c97d5f in __pthread_once_slow () at /lib64/libc.so.6
#9  0x00007fffef410f6c in JSC::initialize() () at /lib64/libjavascriptcoregtk-4.0.so.18
#10 0x00007fffeea616e9 in JSGlobalContextCreate () at /lib64/libjavascriptcoregtk-4.0.so.18
#11 0x00007ffff65426ad in  () at /usr/lib64/libproxy-0.4.18/modules/pacrunner_webkit.so
#12 0x00007ffff71ea274 in libproxy::pacrunner_extension::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libproxy::url const&) () at /lib64/libproxy.so.1
#13 0x00007ffff71f2eaf in px_proxy_factory_get_proxies () at /lib64/libproxy.so.1
```

I don't know if there's any function you're missing calling to shut down that context. If there's nothing, can you forward the report to webkitgtk so they shut down their threads and wait for that shut down on module unload?

A workaround is to never unload plugins. libjavascriptcoregtk can also opt to be `RTLD_NODELETE` if they can't fix this.

**Comment by janbrummer** [comment]
Closing this one as obsolete. Libproxy has been rewritten from scratch and this is no longer part of the code.
