### ISSUE TITLE
GNOME Software segfault

### ISSUE THREAD

**Issue by janbrummer** [libproxy/libproxy#218]
```
(gdb) bt
#0  0x00007f7ce51ff836 in duk_unicode_encode_cesu8 () at /lib64/libduktape.so.207
#1  0x00007f7ce520a5ff in duk.appendbuffer () at /lib64/libduktape.so.207
#2  0x00007f7ce522195a in duk.advance_helper () at /lib64/libduktape.so.207
#3  0x00007f7ce522328c in duk.parse_func_body () at /lib64/libduktape.so.207
#4  0x00007f7ce52259de in duk.js_compile_raw () at /lib64/libduktape.so.207
#5  0x00007f7ce5205e2b in duk_handle_safe_call () at /lib64/libduktape.so.207
#6  0x00007f7ce5212995 in duk_js_compile () at /lib64/libduktape.so.207
#7  0x00007f7ce521bd59 in duk.do_compile () at /lib64/libduktape.so.207
#8  0x00007f7ce5205e2b in duk_handle_safe_call () at /lib64/libduktape.so.207
#9  0x00007f7ce521bdf1 in duk_compile_raw () at /lib64/libduktape.so.207
#10 0x00007f7ce521edd2 in duk_eval_raw () at /lib64/libduktape.so.207
#11 0x00007f7ce5284646 in px_pacrunner_duktape_set_pac (pacrunner=0x7f7cbc02a6a0, pac_data=0x7f7cbc04d720)
    at ../src/backend/plugins/pacrunner-duktape/pacrunner-duktape.c:178
#12 0x00007f7ce527fa72 in px_manager_run_pac (pacrunner=0x7f7cbc02a6a0, pac=0x7f7cbc04d720, uri=0x7f7c84010920, builder=0x7f7c8400cdf0)
    at ../src/backend/px-manager.c:436
#13 0x00007f7ce528046a in px_manager_get_proxies_sync
    (self=0x7f7cbc024530, url=0x7f7c84009cb0 "https://fwupd.org/downloads/0b8ca8891a5be45d5d35b839329f03ed29effc565da1d0ec449076b5e481fee8-S73_01130000.cab", error=0x7f7cab6ac370) at ../src/backend/px-manager.c:592
#14 0x00007f7ce5c2f3a1 in px_proxy_factory_get_proxies
    (self=0x7f7cbc029fa0, url=0x7f7c84009cb0 "https://fwupd.org/downloads/0b8ca8891a5be45d5d35b839329f03ed29effc565da1d0ec449076b5e481fee8-S73_01130000.cab") at ../src/libproxy/proxy.c:61
#15 0x00007f7ce6d51608 in Curl_libproxy_detect_proxy () at /lib64/libcurl.so.4
#16 0x00007f7ce6db9fd4 in detect_proxy () at /lib64/libcurl.so.4
#17 0x00007f7ce6dbaab1 in create_conn_helper_init_proxy () at /lib64/libcurl.so.4
#18 0x00007f7ce6dbcc90 in create_conn () at /lib64/libcurl.so.4
#19 0x00007f7ce6dbd9f3 in Curl_connect () at /lib64/libcurl.so.4
#20 0x00007f7ce6d8acec in multi_runsingle () at /lib64/libcurl.so.4
#21 0x00007f7ce6d8c461 in curl_multi_perform () at /lib64/libcurl.so.4
#22 0x00007f7ce6d58887 in easy_transfer () at /lib64/libcurl.so.4
#23 0x00007f7ce6d58aad in easy_perform () at /lib64/libcurl.so.4
#24 0x00007f7ce6d58afe in curl_easy_perform () at /lib64/libcurl.so.4
#25 0x00007f7cd41b60b6 in fwupd_client_download_http () at /lib64/libfwupd.so.2
#26 0x00007f7cd41b6703 in fwupd_client_download_bytes_thread_cb.lto_priv () at /lib64/libfwupd.so.2
#27 0x00007f7ce7fd4fa4 in g_task_thread_pool_thread () at /lib64/libgio-2.0.so.0
#28 0x00007f7ce7e02fb2 in g_thread_pool_thread_proxy.lto_priv () at /lib64/libglib-2.0.so.0
#29 0x00007f7ce7e00893 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#30 0x00007f7ce7031907 in start_thread () at /lib64/libc.so.6
#31 0x00007f7ce70b7870 in clone3 () at /lib64/libc.so.6

```

**Comment by janbrummer** [comment]
Note: This happens with a modified version of curl supporting libproxy, so this is an in progress issue.

**Comment by janbrummer** [comment]
Cannot reproduce with recent curl patches.
